modLoader="javafml"
loaderVersion="[36,)"
license="LGPL v2.1"

[[mods]]
modId="bingo"
version="${file.jarVersion}"
displayName="Modded Bingo"
credits=""
authors=""
description='''
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.bingo]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingo]]
    modId="bookshelf"
    mandatory=true
    versionRange="[10.0.1,)"
    ordering="AFTER"
    side="BOTH"