modLoader="javafml"
loaderVersion="[35,)"
license="LGPL v2.1"

[[mods]]
modId="bingo"
version="${file.jarVersion}"
displayName="Modded Bingo"
credits=""
authors=""
description='''
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.bingo]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bingo]]
    modId="bookshelf"
    mandatory=true
    versionRange="[9.3.18,)"
    ordering="AFTER"
    side="BOTH"